<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260315224344 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE assessment (id UUID NOT NULL, total_score INT NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, stress_level INT DEFAULT NULL, owner_id UUID NOT NULL, quiz_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F7523D707E3C61F9 ON assessment (owner_id)');
        $this->addSql('CREATE INDEX IDX_F7523D70853CD175 ON assessment (quiz_id)');
        $this->addSql('CREATE TABLE assessment_response (assessment_id UUID NOT NULL, response_id UUID NOT NULL, PRIMARY KEY (assessment_id, response_id))');
        $this->addSql('CREATE INDEX IDX_420D1ADDDD3DD5F1 ON assessment_response (assessment_id)');
        $this->addSql('CREATE INDEX IDX_420D1ADDFBF32840 ON assessment_response (response_id)');
        $this->addSql('CREATE TABLE category (id UUID NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE documentation (id UUID NOT NULL, title VARCHAR(255) NOT NULL, content TEXT NOT NULL, is_active BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE documentation_category (documentation_id UUID NOT NULL, category_id UUID NOT NULL, PRIMARY KEY (documentation_id, category_id))');
        $this->addSql('CREATE INDEX IDX_45A7AD84C703EEC9 ON documentation_category (documentation_id)');
        $this->addSql('CREATE INDEX IDX_45A7AD8412469DE2 ON documentation_category (category_id)');
        $this->addSql('CREATE TABLE question (id UUID NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, is_active BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE quiz (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, is_active BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE quiz_question (quiz_id INT NOT NULL, question_id UUID NOT NULL, PRIMARY KEY (quiz_id, question_id))');
        $this->addSql('CREATE INDEX IDX_6033B00B853CD175 ON quiz_question (quiz_id)');
        $this->addSql('CREATE INDEX IDX_6033B00B1E27F6BF ON quiz_question (question_id)');
        $this->addSql('CREATE TABLE quiz_category (quiz_id INT NOT NULL, category_id UUID NOT NULL, PRIMARY KEY (quiz_id, category_id))');
        $this->addSql('CREATE INDEX IDX_D088E084853CD175 ON quiz_category (quiz_id)');
        $this->addSql('CREATE INDEX IDX_D088E08412469DE2 ON quiz_category (category_id)');
        $this->addSql('CREATE TABLE response (id UUID NOT NULL, points INT NOT NULL, position INT NOT NULL, description TEXT DEFAULT NULL, is_active BOOLEAN NOT NULL, question_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3E7B0BFB1E27F6BF ON response (question_id)');
        $this->addSql('CREATE TABLE "user" (id UUID NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, last_connection TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, creation_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, failed_attempt INT DEFAULT NULL, locked_until TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_active BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE TABLE user_documentation (user_id UUID NOT NULL, documentation_id UUID NOT NULL, PRIMARY KEY (user_id, documentation_id))');
        $this->addSql('CREATE INDEX IDX_9D5B046BA76ED395 ON user_documentation (user_id)');
        $this->addSql('CREATE INDEX IDX_9D5B046BC703EEC9 ON user_documentation (documentation_id)');
        $this->addSql('CREATE TABLE user_quiz (user_id UUID NOT NULL, quiz_id INT NOT NULL, PRIMARY KEY (user_id, quiz_id))');
        $this->addSql('CREATE INDEX IDX_DE93B65BA76ED395 ON user_quiz (user_id)');
        $this->addSql('CREATE INDEX IDX_DE93B65B853CD175 ON user_quiz (quiz_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE assessment ADD CONSTRAINT FK_F7523D707E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE assessment ADD CONSTRAINT FK_F7523D70853CD175 FOREIGN KEY (quiz_id) REFERENCES quiz (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE assessment_response ADD CONSTRAINT FK_420D1ADDDD3DD5F1 FOREIGN KEY (assessment_id) REFERENCES assessment (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE assessment_response ADD CONSTRAINT FK_420D1ADDFBF32840 FOREIGN KEY (response_id) REFERENCES response (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE documentation_category ADD CONSTRAINT FK_45A7AD84C703EEC9 FOREIGN KEY (documentation_id) REFERENCES documentation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE documentation_category ADD CONSTRAINT FK_45A7AD8412469DE2 FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE quiz_question ADD CONSTRAINT FK_6033B00B853CD175 FOREIGN KEY (quiz_id) REFERENCES quiz (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE quiz_question ADD CONSTRAINT FK_6033B00B1E27F6BF FOREIGN KEY (question_id) REFERENCES question (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE quiz_category ADD CONSTRAINT FK_D088E084853CD175 FOREIGN KEY (quiz_id) REFERENCES quiz (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE quiz_category ADD CONSTRAINT FK_D088E08412469DE2 FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE response ADD CONSTRAINT FK_3E7B0BFB1E27F6BF FOREIGN KEY (question_id) REFERENCES question (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_documentation ADD CONSTRAINT FK_9D5B046BA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_documentation ADD CONSTRAINT FK_9D5B046BC703EEC9 FOREIGN KEY (documentation_id) REFERENCES documentation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_quiz ADD CONSTRAINT FK_DE93B65BA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_quiz ADD CONSTRAINT FK_DE93B65B853CD175 FOREIGN KEY (quiz_id) REFERENCES quiz (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE assessment DROP CONSTRAINT FK_F7523D707E3C61F9');
        $this->addSql('ALTER TABLE assessment DROP CONSTRAINT FK_F7523D70853CD175');
        $this->addSql('ALTER TABLE assessment_response DROP CONSTRAINT FK_420D1ADDDD3DD5F1');
        $this->addSql('ALTER TABLE assessment_response DROP CONSTRAINT FK_420D1ADDFBF32840');
        $this->addSql('ALTER TABLE documentation_category DROP CONSTRAINT FK_45A7AD84C703EEC9');
        $this->addSql('ALTER TABLE documentation_category DROP CONSTRAINT FK_45A7AD8412469DE2');
        $this->addSql('ALTER TABLE quiz_question DROP CONSTRAINT FK_6033B00B853CD175');
        $this->addSql('ALTER TABLE quiz_question DROP CONSTRAINT FK_6033B00B1E27F6BF');
        $this->addSql('ALTER TABLE quiz_category DROP CONSTRAINT FK_D088E084853CD175');
        $this->addSql('ALTER TABLE quiz_category DROP CONSTRAINT FK_D088E08412469DE2');
        $this->addSql('ALTER TABLE response DROP CONSTRAINT FK_3E7B0BFB1E27F6BF');
        $this->addSql('ALTER TABLE user_documentation DROP CONSTRAINT FK_9D5B046BA76ED395');
        $this->addSql('ALTER TABLE user_documentation DROP CONSTRAINT FK_9D5B046BC703EEC9');
        $this->addSql('ALTER TABLE user_quiz DROP CONSTRAINT FK_DE93B65BA76ED395');
        $this->addSql('ALTER TABLE user_quiz DROP CONSTRAINT FK_DE93B65B853CD175');
        $this->addSql('DROP TABLE assessment');
        $this->addSql('DROP TABLE assessment_response');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE documentation');
        $this->addSql('DROP TABLE documentation_category');
        $this->addSql('DROP TABLE question');
        $this->addSql('DROP TABLE quiz');
        $this->addSql('DROP TABLE quiz_question');
        $this->addSql('DROP TABLE quiz_category');
        $this->addSql('DROP TABLE response');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_documentation');
        $this->addSql('DROP TABLE user_quiz');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
