<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260316172304 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE stress_threshold (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, level VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, min_score INT NOT NULL, max_score INT DEFAULT NULL, description TEXT NOT NULL, advice TEXT NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE stress_threshold');
    }
}
