server {
    listen 80;
    server_name _;

    root /var/www/html/public;
    index index.php;

    client_max_body_size 20M;

    # Logs (stdout/stderr pour Docker)
    access_log /dev/stdout;
    error_log  /dev/stderr;

    # Fichierss statiques : servis directement s'ils existent
    location / {
        try_files $uri /index.php$is_args$args;
    }

    # Front controller Symfony
    location ~ ^/index\.php(/|$) {
        fastcgi_pass php:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $document_root;

        # Empêche d'exécuter d'autres fichiers .php que index.php
        internal;
    }

    # Sécurité : bloque l'accès direct à tout autre .php
    location ~ \.php$ {
        return 404;
    }

    # Cache long pour les assets statiques (css, js, images, fonts)
    location ~* \.(?:css|js|mjs|map|jpg|jpeg|png|gif|ico|svg|webp|woff|woff2|ttf|eot)$ {
        expires 7d;
        add_header Cache-Control "public, immutable";
        access_log off;
        try_files $uri =404;
    }

    # Bloque l'accès aux fichiers/dossiers cachés (.git, .env, etc.)
    location ~ /\. {
        deny all;
    }
}
